# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
language: cpp
sudo: required

matrix:
    include:
        - dist: trusty
          compiler: gcc
          env: WXGTK_PACKAGE=libwxgtk2.8-dev
        - dist: trusty
          compiler: gcc
          env: WXGTK_PACKAGE=libwxgtk3.0-dev

branches:
    only:
        - master

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y $WXGTK_PACKAGE
    - autoreconf

script:
    - set -e && echo 'Configuring...' && echo -en 'travis_fold:start:script.configure\\r'
    - ./configure
    - echo -en 'travis_fold:end:script.configure\\r'
    - echo 'Building...' && echo -en 'travis_fold:start:script.build\\r'
    - make
    - echo -en 'travis_fold:end:script.build\\r'
    - echo 'Installing...' && echo -en 'travis_fold:start:script.install\\r'
    - sudo make install
    - echo -en 'travis_fold:end:script.install\\r'
